# Created with YamlCreate.ps1 v2.4.1 $debug=QUSU.CRLF.5-1-26100-461.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: WatchGuardTechnologies.WatchGuardSystemManager
PackageVersion: 12.11.1
MinimumOSVersion: 10.0.0.0
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x86
  InstallerUrl: https://cdn.watchguard.com/SoftwareCenter/Files/WSM/12_11/wsm_12_11.exe
  InstallerSha256: 3e336d93d0f3df16f2f63388adf29b05ee5f69a637a4b4a95facfbb826ac9470
  ProductCode: WatchGuard System Manager 12.11_is1
ManifestType: installer
ManifestVersion: 1.6.0
